clone:
  path: github.com/drone-plugins
  recursive: true

build:
  image: armhfbuild/golang:1.5
  environment:
    - GO15VENDOREXPERIMENT=1
    - GOOS=linux
    - GOARCH=arm
    - CGO_ENABLED=0
  commands:
    - git clone --single-branch https://github.com/drone-plugins/drone-email
    - cd drone-email
    - sed -i 's/FROM alpine/FROM armhfbuild\/alpine/' Dockerfile
    - go get
    - go build
    - go test

publish:
  docker:
    context: drone-email
    file: drone-email/Dockerfile
    username: $$DOCKER_USER
    email: $$DOCKER_EMAIL
    password: $$DOCKER_PASSWORD
    repo: armhfplugins/drone-email
    storage_driver: overlay
    when:
      repo: armhf-drone-plugins/drone-email
      branch: master

notify:
  slack:
    webhook_url: $$SLACK_WEBHOOK_URL
    channel: armhf

plugin:
  name: Email
  desc: Send build status notifications via Email
  type: notify
  image: armhfplugins/drone-email
  labels:
    - email
